### ISSUE TITLE
[Math.floor(Math.random() use

### ISSUE THREAD

**Issue by luluwelborn** [luluwelborn/project-2#7]
I am trying to get one random joke from an array onto my homepage. Currently I am getting a random letter on multiple lines. Can you help me understand how to change my function to grab one joke?

```
function displayJokes(jokesPassedIn) {
	var sentenceHTML = "";
	jokesPassedIn.forEach(function(joke) {
		sentenceHTML = sentenceHTML + '<p>' + joke.sentence[Math.floor(Math.random()*joke.sentence.length)] + '</p>';
		
	});
	$('#sentence').append(sentenceHTML);
	console.log(displayJokes(joke.sentence));
};

```

**Comment by stefems** [comment]
objectThatHasProperties.propertyName gives us the propertyName of the objectThatHasProperties

the dot gives us a thing that exists in a thing.
