### ISSUE TITLE
Deploying to Heroku successful in terminal and app activity, not updating in browser

### ISSUE THREAD

**Issue by luluwelborn** [luluwelborn/project-2#8]
When I git push origin master from terminal, the updates are successful in my github repo.
When I git push heroku master from terminal it's reads as successful, but I'm not seeing the changes in the browser. In the app/activity tab within heroku it says the changes have been made.

**Comment by stefems** [comment]
Can you try to make a super simple change (like a console.log() somewhere) just to make sure that the code is being pushed?

**Comment by luluwelborn** [comment]
The app is updating successfully, but the main page's data that shows up locally does not show up in heroku.

**Comment by stefems** [comment]
So it has to do with data, not code features! Where does the data come from when you're testing things locally? Is the db being used locally the same db that is on heroku?

**Comment by stefems** [comment]
I ask these questions to get you thinking about why the data isn't on heroku!

**Comment by luluwelborn** [comment]
I'm running my local MongoDB for local testing, as far as Heroku I don't see a reference to a DB in the build, but I believe it's on their own DB.

**Comment by luluwelborn** [comment]
My actual issue was that I could see my random joke on the main page locally, and not in heroku because I hadn't written anything in my json file to let heroku know it also needed to get data from the seed file.
