### ISSUE TITLE
Need to save a joke to user data, store it, and push it to front end

### ISSUE THREAD

**Issue by luluwelborn** [luluwelborn/project-2#9]
Right now a random joke appears on refresh on the homepage of my app. I want the 'save joke' button to grab that joke id, add it to the user info in the db and send it back to a new page in the app.

I started a function userJokes() function and some code in the document.ready function, but I've complicated it to the point I'm lost on the path I need to take.

The jokes come from my seed.js file, app.js is my server and public/main.js has all the functions for getting data on the page.

**Comment by ZebGirouard** [comment]
Off to a good start on this, keep it up Lauren!
